config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'posts#index'

  get     '/login', to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :users
  resources :posts do
    resources :comments
  end
  resources :comments
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments

  belongs_to :user

  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 140 }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: [:update, :edit, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      flash[:success] = "post created successfully"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    @post.update(post_params)
    if @post.save
      flash[:success] = "post edited suceessfully"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:user_id, :title, :description)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <h3><%= post.title %></h3>
  <%= post.description %><br>
  <span>
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span><br>
  <div class="options col-sm-12 no-padding pd-tp-5 pull-right">
    <% if post.user == current_user %>
      <%= link_to 'Edit Post', edit_post_path(post.id) %>
      <span>|</span>
      <%= link_to 'Delete Post', post_path(post.id), method: :delete %>
    <% end %>
  </div>
  <% post.comments.each do |comment| %>
    <%= link_to User.find(comment.user_id).name %>: 
    <%= comment.text %>
    <% if comment.user == current_user %>
      <%= link_to 'Delete', comment_path(post_id: post.id, id: comment.id), method: :delete %>
    <% end %>
    <br>
  <% end %>
</li>

app/views/posts/edit.html.erb
<div class="col-sm-12">
  <div class="update-profile col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
    <h1>Edit post</h1>

    <%= simple_form_for @post do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="article col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
    <div class="row">  
      <div class="user-details col-sm-12">
        <div class="username col-sm-6 no-padding">
          <%= post.user.name %>
        </div>
        <div class="posted-date text-right col-sm-6 no-padding">
          <%= time_ago_in_words(post.created_at) %> ago
        </div>
      </div>
    </div>
    
    <div class="post col-sm-12 no-padding">
      <h3><%= post.title %></h3>
      <div class="description col-sm-12">
        <%= post.description %>
      </div>
    </div>

    <div class="options col-sm-12 no-padding pd-tp-5">
      <% if post.user == current_user %>
        <%= link_to 'Edit Post', edit_post_path(post.id) %>
        <span>|</span>
        <%= link_to 'Delete Post', post_path(post.id), method: :delete %>
      <% end %>
    </div>

    <br>

    <div class="comments col-sm-12 no-padding">
      <h4>Comments</h4>
      <% post.comments.each do |comment| %>
        <%= link_to User.find(comment.user_id).name, user_path(User.find(comment.user_id)) %>: 
        <%= comment.text %>
        <% if comment.user == current_user %>
          <%= link_to 'Delete', comment_path(post_id: post.id, id: comment.id), class: 'delete-cmt', method: :delete %>
        <% end %>
        <br>
      <% end %>
    </div>

    <div class="comment-form col-sm-12 no-padding">
      <% if logged_in? %>
        <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
          <%= f.input :text, placeholder: "Add your comment" %>
          <%= f.submit 'Post' %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="col-sm-12">
  <div class="update-profile col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
    <h1>Add new post</h1>
    <%= simple_form_for @post do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.submit 'Post' %>
    <% end %>
  </div>
</div>